import Head from 'next/head'

export default function Home() {  
  return (
    <div>
      <Head>
        <title>lhab ru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">
          Lhab ru
          <span>Developer&apos;s island</span>
        </h1>

        <div className='color'>
          <div className='color-one'></div>
          <div className='color-two'></div>
          <div className='color-three'></div>
          <div className='color-four'></div>
          <div className='color-five'></div>
        </div>
      </main>
    </div>
  )
}
