import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>lhab ru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Lhab ru - service in developer <Link href="/news">news demo pages</Link>
        </h1>
        <p>
          Settings deploy (CI/CD)
        </p>
      </main>
    </div>
  )
}
