import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function News() {
  return (
    <div className={styles.container}>
      <Head>
        <title>News test pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          News test pages <Link href='/'>Back home</Link>
        </h1>
      </main>
    </div>
  )
}